trigger: none

pool: myagentpool
steps:
- task: TerraformInstaller@1
  displayName: Terraform ka latest version
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: Terra Initialize
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'SCN_PRIME'
    backendAzureRmStorageAccountName: 'mystgforpipe1'
    backendAzureRmContainerName: 'mycontain1'
    backendAzureRmKey: 'pipecicd.tfstate'
- task: TerraformTask@5
  displayName: Terra Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'SCN_PRIME'
- task: TerraformTask@5
  displayName: Terra Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'SCN_PRIME'


